const LOADED_DATA = 'LOADED_DATA';
const DELETE_LIST_ITEM = 'DELETE_LIST_ITEM';
const DELETE_CASE_ITEM = 'DELETE_CASE_ITEM';
const ADD_DONE = 'ADD_DONE';
const GET_DATA_AUTHORIZATION = 'GET_DATA_AUTHORIZATION';
const LOG_OUT = 'LOG_OUT';
const ADD_NEW_CASE = 'ADD_NEW_CASE';

export {
    LOADED_DATA, 
    DELETE_LIST_ITEM,  DELETE_CASE_ITEM, ADD_DONE,
    GET_DATA_AUTHORIZATION, LOG_OUT, ADD_NEW_CASE
};